#!/usr/bin/env python3

""" ironoxide """

import argparse
import logging
from pathlib import Path
from time import perf_counter

import ironoxide

logger = logging.getLogger(__name__)
start_time = perf_counter()
logger.info('Found ironoxide at ' + str(Path(ironoxide.__file__)))

parser = argparse.ArgumentParser(description='i am ironoxide')
parser.add_argument('-t', '--test', help='test flag, runs specified test')
parser.add_argument('-b', '--bootstrap', help='enables bootstrap mode', action='store_true')
parser.add_argument('-p', '--purge', help='purges p2p database', action='store_true')

args = parser.parse_args()    

if args:
    if args.bootstrap:
        # enable bootstrap mode
        bootstrap = True
    else:
        bootstrap = False

    logger.info(f"executed in {round(perf_counter() - start_time, 3)}s")
