#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK

""" ironoxide """

import argparse
import logging
import os
from pathlib import Path
from time import perf_counter

import ironoxide
from ironoxide import convert, filemanager

start_time = perf_counter()

logging.basicConfig(level=logging.DEBUG, format=('%(asctime)s %(levelname)s %(name)s | %(message)s'))
logger = logging.getLogger('ironoxide-cli')
logger.info('Found ironoxide at ' + str(Path(ironoxide.__file__)))


def is_valid_file(parser, arg):
    if not os.path.isfile(arg):
        parser.error(f'The file {arg} does not exist!')
    else:
        return arg


parser = argparse.ArgumentParser(description='i am ironoxide')
parser.add_argument('--convert', '-c', help='Converts provided context pdf to jsonl and uploads to OpenAI, and assosiates with provided course', required=False, metavar="FILE", type=lambda x: is_valid_file(parser, x))

args = parser.parse_args()

if args:
    if args.convert is not None:
        convert.main(args.convert)

logger.info(f"executed in {round(perf_counter() - start_time, 3)}s")

# https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html
