# Generated by Django 4.0.4 on 2022-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironoxide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
